In [57]:
import numpy as np
import sympy
import time
import math
from scipy import integrate
import timeit

In [58]:
#derivace v bodě

def der_cla(fce,bod):
    zacatek = time.perf_counter()
    h = 0.001
    derivace = (fce(bod+h)-fce(bod-h))/(2*h)
    konec = time.perf_counter()
    cas = konec-zacatek
    return derivace, 1000*cas

def der_s(fce,bod):
    zacatek = time.perf_counter()
    derivace = sympy.diff(fce,x)
    vysledek = derivace.evalf(subs={x: bod})
    konec = time.perf_counter()
    cas = konec-zacatek
    return vysledek, 1000*cas

x = sympy.symbols("x")

print(f"V klasickém pythonu trvala derivace {der_cla(lambda x: 5*x**4*math.sin(x),3)[1]} milisekund.")
print(f"V knihovně sympy trvala derivace {der_s(5*x**4*sympy.sin(x),3)[1]} milisekund.")

V klasickém pythonu trvala derivace 0.008699949830770493 milisekund.
V knihovně sympy trvala derivace 1.18789984844625 milisekund.


In [59]:
#skalární součin

def ska_cla(v1,v2):
    zacatek = time.perf_counter()
    celkem = 0
    for i in range(len(v1)):
        mezi = v1[i]*v2[i]
        celkem += mezi
    konec = time.perf_counter()
    cas = konec-zacatek
    return celkem, 1000*cas
            
def ska_num(v1,v2):
    zacatek = time.perf_counter()
    vysledek = np.dot(v1,v2)
    konec = time.perf_counter()
    cas = konec-zacatek
    return vysledek, 1000*cas

v1 = [-1, 5, 8, 4, -6]
v2 = [9, 7, -2, 1, 12]

print(f"V klasickém pythonu trval výpočet skalárního součinu {ska_cla(v1,v2)[1]} milisekund.")
print(f"V knihovně numpy trval výpočet skalárního součinu {ska_num(v1,v2)[1]} milisekund.")


V klasickém pythonu trval výpočet skalárního součinu 0.009999843314290047 milisekund.
V knihovně numpy trval výpočet skalárního součinu 0.044599873945117 milisekund.


In [60]:
#faktoriál

def fakt_cla(x):
    zacatek = time.perf_counter()
    celkem = 1
    for i in range(1,x+1):
        celkem *= i
    konec = time.perf_counter()
    cas = konec-zacatek
    return celkem, 1000*cas

def fakt_mat(x):
    zacatek = time.perf_counter()
    vysledek = math.factorial(x)
    konec = time.perf_counter()
    cas = konec-zacatek
    return vysledek, 1000*cas

def fakt_s(x):
    zacatek = time.perf_counter()
    vysledek = sympy.factorial(x)
    konec = time.perf_counter()
    cas = konec-zacatek
    return vysledek, 1000*cas

faktorial=5
print(f"V klasickém pythonu trval výpočet faktorialu {fakt_cla(faktorial)[1]} milisekund.")
print(f"V knihovně math trval výpočet faktorialu {fakt_mat(faktorial)[1]} milisekund.")
print(f"V knihovně sympy trval výpočet faktorialu {fakt_s(faktorial)[1]} milisekund.")

V klasickém pythonu trval výpočet faktorialu 0.005800044164061546 milisekund.
V knihovně math trval výpočet faktorialu 0.001800013706088066 milisekund.
V knihovně sympy trval výpočet faktorialu 0.00609993003308773 milisekund.


In [61]:
#určitý integrál

def inter_clas(f,a,b):
    zacatek = time.perf_counter()
    dx = 0.1
    x = a
    vysledek = 0
    while x < b:
        vysledek += dx * (f(x)+f(x+dx))/2
        x += dx
    konec = time.perf_counter()
    cas = konec-zacatek
    return vysledek, 1000*cas

def inter_num(f,a,b):
    zacatek = time.perf_counter()
    dx = 0.1
    x = np.arange(a, b+dx, dx)
    y = f(x)
    vysledek = np.trapz(y,dx=dx)
    konec = time.perf_counter()
    cas = konec-zacatek
    return vysledek, 1000*cas

def inter_sci(f,a,b):
    zacatek = time.perf_counter()
    dx = 0.1
    x = np.arange(a, b+dx, dx)
    y = f(x)
    vysledek = integrate.simpson(y=y, x=x)
    konec = time.perf_counter()
    cas = konec-zacatek
    return vysledek, 1000*cas

funkce = (lambda x: -3*x**2+5*x+5)

print(f"V klasickém pythonu trval výpočet určitého integrálu {inter_clas(funkce,0,2)[1]} milisekund.")
print(f"V knihovně numpy trval výpočet určitého integrálu {inter_num(funkce,0,2)[1]} milisekund.")
print(f"V knihovně scipy trval výpočet určitého integrálu {inter_sci(funkce,0,2)[1]} milisekund.")

V klasickém pythonu trval výpočet určitého integrálu 0.04910002462565899 milisekund.
V knihovně numpy trval výpočet určitého integrálu 0.11770008131861687 milisekund.
V knihovně scipy trval výpočet určitého integrálu 0.2809001598507166 milisekund.


In [62]:
#násobení matic

def nasm_clas(A,B):
    zacatek = time.perf_counter()
    C = []
    for i in range(len(A)):
        celkem=0
        for j in range(len(B)):
            celkem+=A[i,j]*B[j,0]
        C.append(celkem)
    vysledek = np.array(C).reshape(3,1)
    konec = time.perf_counter()
    cas = konec-zacatek
    return vysledek, 1000*cas

def nasm_clas2(A,B):
    zacatek = time.perf_counter()
    vysledek = A @ B
    konec = time.perf_counter()
    cas = konec-zacatek
    return vysledek, 1000*cas

def nasm_num(A,B):
    zacatek = time.perf_counter()
    vysledek = np.matmul(A,B)
    konec = time.perf_counter()
    cas = konec-zacatek
    return vysledek, 1000*cas

A = np.array([[2,0,6],[1,5,4],[2,4,0]])
B = np.array([[-1],[5],[2]])

print(f"V klasickém pythonu trvalo násobení matic {nasm_clas(A,B)[1]} milisekund.")
print(f"V klasickém pythonu s jinou funkcí trvalo násobení matic {nasm_clas2(A,B)[1]} milisekund.")
print(f"V knihovně numpy trvalo násobení matic {nasm_num(A,B)[1]} milisekund.")

V klasickém pythonu trvalo násobení matic 0.0350000336766243 milisekund.
V klasickém pythonu s jinou funkcí trvalo násobení matic 0.024900073185563087 milisekund.
V knihovně numpy trvalo násobení matic 0.04300009459257126 milisekund.


In [63]:
x = sympy.symbols("x")
#derivace
print("derivace")
print("classic:",der_cla(lambda x: 5*x**4*math.sin(x),3))
print("sympy:\t",der_s(5*x**4*sympy.sin(x),3))
#skalarní součin
print("skalární součin")
print("classic:",ska_cla(v1,v2))
print("numpy:\t",ska_num(v1,v2))
#faktoriál
print("faktoriál")
print("classic:",fakt_cla(faktorial))
print("math:\t",fakt_mat(faktorial))
print("sympy:\t",fakt_s(faktorial))
#integrál
print("integrál")
print("classic:",inter_clas(funkce,0,2))
print("numpy:\t",inter_num(funkce,0,2))
print("scipy:\t",inter_sci(funkce,0,2))
#násobení matic
print("násobení matic")
print("classic:\n",nasm_clas(A,B)[0],"\t",nasm_clas(A,B)[1])
print("classic:\n",nasm_clas2(A,B))
print("numpy:\n",nasm_num(A,B))

derivace
classic: (-324.742386879457, 0.016700010746717453)
sympy:	 (-324.742156770852, 1.3859998434782028)
skalární součin
classic: (-58, 0.03700004890561104)
numpy:	 (-58, 0.15380000695586205)
faktoriál
classic: (120, 0.009800074622035027)
math:	 (120, 0.003300141543149948)
sympy:	 (120, 0.00809994526207447)
integrál
classic: (11.989999999999997, 0.07560010999441147)
numpy:	 (11.989999999999998, 0.16570021398365498)
scipy:	 (12.0, 0.4827000666409731)
násobení matic
classic:
 [[10]
 [32]
 [18]] 	 0.02550007775425911
classic:
 (array([[10],
       [32],
       [18]]), 0.018200138583779335)
numpy:
 (array([[10],
       [32],
       [18]]), 0.016399892047047615)
